# Generated by Django 5.2.3 on 2025-06-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Recrutador',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='usuario',
            new_name='recrutador',
        ),
        migrations.AddField(
            model_name='entrevista',
            name='recrutador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas', to='core.recrutador'),
        ),
    ]
